---
kind: pipeline
name: building-pypi-builder-aarch64-image

platform:
  os: linux
  arch: arm64

docker_build_manylinux: &docker_build_manylinux
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    context: pypi
    repo: drakkarsoftware/pypi-builder
    dockerfile: pypi/manylinux/aarch64/Dockerfile

steps:
- name: docker_build_python_3_7
  <<: *docker_build_manylinux
  build_args:
  - PYTHON_VERSION=3.7
  tags:
  - python-3.7-manylinux-aarch64
- name: docker_build_python_3_8
  <<: *docker_build_manylinux
  build_args:
  - PYTHON_VERSION=3.8
  tags:
  - python-3.8-manylinux-aarch64
- name: docker_build_python_3_9
  <<: *docker_build_manylinux
  build_args:
  - PYTHON_VERSION=3.9
  tags:
  - python-3.9-manylinux-aarch64

---
kind: pipeline
name: building-pypi-numpy-tulipy-on-arm64

workspace:
  base: /project

platform:
  os: linux
  arch: arm64

steps:
- name: nexus_pypi_publish_numpy
  pull: always
  image: drakkarsoftware/pypi-builder:manylinux-aarch64
  environment:
    OCTOBOT_PYPI_URL:
      from_secret: OCTOBOT_PYPI_URL
    PYPI_DOWNLOAD: numpy
    PYPI_USERNAME:
      from_secret: nexus_pypi_username
    PYPI_PASSWORD:
      from_secret: nexus_pypi_password
    PYPI_REPOSITORY: https://www.tentacles.octobot.online/repository/octobot_pypi/
- name: nexus_pypi_publish_tulipy
  pull: always
  image: drakkarsoftware/pypi-builder:manylinux-aarch64
  environment:
    OCTOBOT_PYPI_URL:
      from_secret: OCTOBOT_PYPI_URL
    PYPI_DOWNLOAD: tulipy
    PYPI_REQUIREMENTS: numpy cython
    PYPI_USERNAME:
      from_secret: nexus_pypi_username
    PYPI_PASSWORD:
      from_secret: nexus_pypi_password
    PYPI_REPOSITORY: https://www.tentacles.octobot.online/repository/octobot_pypi/

---
kind: pipeline
name: building-pypi-gevent-on-arm64

workspace:
  base: /project

platform:
  os: linux
  arch: arm64

steps:
- name: nexus_pypi_publish
  pull: always
  image: drakkarsoftware/pypi-builder:manylinux-aarch64
  environment:
    OCTOBOT_PYPI_URL:
      from_secret: OCTOBOT_PYPI_URL
    PYPI_DOWNLOAD: gevent
    PYPI_USERNAME:
      from_secret: nexus_pypi_username
    PYPI_PASSWORD:
      from_secret: nexus_pypi_password
    PYPI_REPOSITORY: https://www.tentacles.octobot.online/repository/octobot_pypi/

---
kind: pipeline
name: building-pypi-lxml-on-arm64

workspace:
  base: /project

platform:
  os: linux
  arch: arm64

steps:
- name: nexus_pypi_publish
  pull: always
  image: drakkarsoftware/pypi-builder:manylinux-aarch64
  environment:
    OCTOBOT_PYPI_URL:
      from_secret: OCTOBOT_PYPI_URL
    PYPI_DOWNLOAD: lxml
    PYPI_USERNAME:
      from_secret: nexus_pypi_username
    PYPI_PASSWORD:
      from_secret: nexus_pypi_password
    PYPI_REPOSITORY: https://www.tentacles.octobot.online/repository/octobot_pypi/

---
kind: pipeline
name: building-pypi-cryptography-cffi-multidict-on-arm64

workspace:
  base: /project

platform:
  os: linux
  arch: arm64

steps:
- name: nexus_pypi_publish_cryptography
  pull: always
  image: drakkarsoftware/pypi-builder:manylinux-aarch64
  environment:
    OCTOBOT_PYPI_URL:
      from_secret: OCTOBOT_PYPI_URL
    PYPI_DOWNLOAD: cryptography
    PYPI_USERNAME:
      from_secret: nexus_pypi_username
    PYPI_PASSWORD:
      from_secret: nexus_pypi_password
    PYPI_REPOSITORY: https://www.tentacles.octobot.online/repository/octobot_pypi/
- name: nexus_pypi_publish_cffi
  pull: always
  image: drakkarsoftware/pypi-builder:manylinux-aarch64
  environment:
    OCTOBOT_PYPI_URL:
      from_secret: OCTOBOT_PYPI_URL
    PYPI_DOWNLOAD: cffi
    PYPI_USERNAME:
      from_secret: nexus_pypi_username
    PYPI_PASSWORD:
      from_secret: nexus_pypi_password
    PYPI_REPOSITORY: https://www.tentacles.octobot.online/repository/octobot_pypi/
- name: nexus_pypi_publish_multidict
  pull: always
  image: drakkarsoftware/pypi-builder:manylinux-aarch64
  environment:
    OCTOBOT_PYPI_URL:
      from_secret: OCTOBOT_PYPI_URL
    PYPI_DOWNLOAD: multidict
    PYPI_USERNAME:
      from_secret: nexus_pypi_username
    PYPI_PASSWORD:
      from_secret: nexus_pypi_password
    PYPI_REPOSITORY: https://www.tentacles.octobot.online/repository/octobot_pypi/
