---
kind: pipeline
name: building-pypi-bdist

workspace:
  base: /project

platform:
  os: linux
  arch: amd64

steps:
- name: pypi_publish
  pull: always
  image: drakkarsoftware/pypi-builder:master
  environment:
    PYPI_USERNAME:
      from_secret: pypi_username
    PYPI_PASSWORD:
      from_secret: pypi_password
    BUILD_TYPE: "SDIST"

---
kind: pipeline
name: building-pypi-on-amd64

workspace:
  base: /project

platform:
  os: linux
  arch: amd64

steps:
- name: pypi_publish
  pull: always
  image: drakkarsoftware/pypi-builder:manylinux-x86_64
  environment:
    PYPI_USERNAME:
      from_secret: pypi_username
    PYPI_PASSWORD:
      from_secret: pypi_password

---
kind: pipeline
name: building-pypi-on-i386

workspace:
  base: /project

platform:
  os: linux
  arch: amd64

steps:
- name: pypi_publish
  pull: always
  image: drakkarsoftware/pypi-builder:manylinux-i686
  environment:
    PYPI_USERNAME:
      from_secret: pypi_username
    PYPI_PASSWORD:
      from_secret: pypi_password

---
kind: pipeline
name: building-pypi-on-arm64

workspace:
  base: /project

platform:
  os: linux
  arch: arm64

steps:
- name: pypi_publish
  pull: always
  image: drakkarsoftware/pypi-builder:manylinux-aarch64
  environment:
    PYPI_USERNAME:
      from_secret: pypi_username
    PYPI_PASSWORD:
      from_secret: pypi_password
