---
kind: pipeline
name: building-pypi-builder-aarch64-image

platform:
  os: linux
  arch: arm64

steps:
- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    context: pypi
    repo: drakkarsoftware/pypi-builder
    dockerfile: pypi/manylinux/aarch64/Dockerfile
    tags:
    - manylinux-aarch64

---
kind: pipeline
name: building-pypi-numpy-tulipy-on-arm64

workspace:
  base: /project

platform:
  os: linux
  arch: arm64

steps:
- name: nexus_pypi_publish_numpy
  pull: always
  image: drakkarsoftware/pypi-builder:manylinux-aarch64
  environment:
    OCTOBOT_PYPI_URL:
      from_secret: OCTOBOT_PYPI_URL
    PYPI_DOWNLOAD: numpy
    PYPI_USERNAME:
      from_secret: nexus_pypi_username
    PYPI_PASSWORD:
      from_secret: nexus_pypi_password
    PYPI_REPOSITORY: https://www.tentacles.octobot.online/repository/octobot_pypi/
- name: nexus_pypi_publish_tulipy
  pull: always
  image: drakkarsoftware/pypi-builder:manylinux-aarch64
  environment:
    OCTOBOT_PYPI_URL:
      from_secret: OCTOBOT_PYPI_URL
    PYPI_DOWNLOAD: tulipy
    PYPI_REQUIREMENTS: numpy cython
    PYPI_USERNAME:
      from_secret: nexus_pypi_username
    PYPI_PASSWORD:
      from_secret: nexus_pypi_password
    PYPI_REPOSITORY: https://www.tentacles.octobot.online/repository/octobot_pypi/

---
kind: pipeline
name: building-pypi-gevent-on-arm64

workspace:
  base: /project

platform:
  os: linux
  arch: arm64

steps:
- name: nexus_pypi_publish
  pull: always
  image: drakkarsoftware/pypi-builder:manylinux-aarch64
  environment:
    OCTOBOT_PYPI_URL:
      from_secret: OCTOBOT_PYPI_URL
    PYPI_DOWNLOAD: gevent
    PYPI_USERNAME:
      from_secret: nexus_pypi_username
    PYPI_PASSWORD:
      from_secret: nexus_pypi_password
    PYPI_REPOSITORY: https://www.tentacles.octobot.online/repository/octobot_pypi/

---
kind: pipeline
name: building-pypi-cryptography-cffi-multidict-on-arm64

workspace:
  base: /project

platform:
  os: linux
  arch: arm64

steps:
- name: nexus_pypi_publish_cryptography
  pull: always
  image: drakkarsoftware/pypi-builder:manylinux-aarch64
  environment:
    OCTOBOT_PYPI_URL:
      from_secret: OCTOBOT_PYPI_URL
    PYPI_DOWNLOAD: cryptography
    PYPI_USERNAME:
      from_secret: nexus_pypi_username
    PYPI_PASSWORD:
      from_secret: nexus_pypi_password
    PYPI_REPOSITORY: https://www.tentacles.octobot.online/repository/octobot_pypi/
- name: nexus_pypi_publish_cffi
  pull: always
  image: drakkarsoftware/pypi-builder:manylinux-aarch64
  environment:
    OCTOBOT_PYPI_URL:
      from_secret: OCTOBOT_PYPI_URL
    PYPI_DOWNLOAD: cffi
    PYPI_USERNAME:
      from_secret: nexus_pypi_username
    PYPI_PASSWORD:
      from_secret: nexus_pypi_password
    PYPI_REPOSITORY: https://www.tentacles.octobot.online/repository/octobot_pypi/
- name: nexus_pypi_publish_multidict
  pull: always
  image: drakkarsoftware/pypi-builder:manylinux-aarch64
  environment:
    OCTOBOT_PYPI_URL:
      from_secret: OCTOBOT_PYPI_URL
    PYPI_DOWNLOAD: multidict
    PYPI_USERNAME:
      from_secret: nexus_pypi_username
    PYPI_PASSWORD:
      from_secret: nexus_pypi_password
    PYPI_REPOSITORY: https://www.tentacles.octobot.online/repository/octobot_pypi/
