---
kind: pipeline
name: building-pypi-numpy-on-arm64

workspace:
  base: /project

platform:
  os: linux
  arch: arm64

steps:
- name: nexus_pypi_publish
  pull: always
  image: drakkarsoftware/pypi-builder:manylinux-aarch64
  environment:
    OCTOBOT_PYPI_URL:
      from_secret: OCTOBOT_PYPI_URL
    PYPI_DOWNLOAD: numpy==1.18.4
    PYPI_USERNAME:
      from_secret: nexus_pypi_username
    PYPI_PASSWORD:
      from_secret: nexus_pypi_password
    PYPI_REPOSITORY: https://www.tentacles.octobot.online/repository/octobot_pypi/

---
kind: pipeline
name: building-pypi-pandas-on-arm64

workspace:
  base: /project

platform:
  os: linux
  arch: arm64

steps:
- name: nexus_pypi_publish
  pull: always
  image: drakkarsoftware/pypi-builder:manylinux-aarch64
  environment:
    OCTOBOT_PYPI_URL:
      from_secret: OCTOBOT_PYPI_URL
    PYPI_DOWNLOAD: pandas==1.0.3
    PYPI_USERNAME:
      from_secret: nexus_pypi_username
    PYPI_PASSWORD:
      from_secret: nexus_pypi_password
    PYPI_REPOSITORY: https://www.tentacles.octobot.online/repository/octobot_pypi/
    PYPI_REQUIREMENTS_FILE_URL: https://raw.githubusercontent.com/pandas-dev/pandas/master/requirements-dev.txt
