---
kind: pipeline
name: octobot-on-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: clone-octobot
  image: alpine
  commands:
    - apk add git
    - git clone https://github.com/Drakkar-Software/OctoBot
    - cd OctoBot

- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: drakkarsoftware/octobot
    tags: test-arch

---
kind: pipeline
name: octobot-on-arm32

platform:
  os: linux
  arch: arm

steps:
- name: clone-octobot
  image: alpine
  commands:
    - apk add git
    - git clone https://github.com/Drakkar-Software/OctoBot
    - cd OctoBot

- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: drakkarsoftware/octobot
    tags: test-arch
