---
kind: pipeline
name: octobot-on-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: drakkarsoftware/octobot
    tags: ${DRONE_COMMIT_BRANCH}

---
kind: pipeline
name: octobot-on-arm32

platform:
  os: linux
  arch: arm

steps:
- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: drakkarsoftware/octobot
    tags: ${DRONE_COMMIT_BRANCH}
