---
kind: pipeline
name: building-pypi-on-arm32

platform:
  os: linux
  arch: arm

steps:
- name: pypi_publish
  image: drakkarsoftware/octobot-builder-pypi:master
  environment:
    PYPI_USERNAME:
      from_secret: pypi_username
    PYPI_PASSWORD:
      from_secret: pypi_password
  volumes:
    - name: project
      path: /drone/src/.git/OctoBot-Builder

volumes:
- name: project
  temp: {}
